### PR TITLE
DM-31959: /nb must be /nb/hub with JH 1.4

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Comment by jonathansick** [comment]
@athornton Are all environments running this new version of JupyterHub, or does it need to be configurable?

**Comment by athornton** [comment]
> @athornton Are all environments running this new version of JupyterHub, or does it need to be configurable?

/nb/hub will work everywhere.

**Review by jonathansick — APPROVED** [review]
Ok, sounds good. I'll merge and tag as 0.4.1 to release the Docker image.

For deployment, do you want to just update the image tag in Phalanx?

**Comment by athornton** [comment]
Yeah, I'll update the tag in Phalanx

**Pull request merged**
